/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./public/**/*.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    colors: {
      transparent: 'transparent',
      'white': '#ffffff',
      'purple': '#3f3cbb',
      'midnight': '#121063',
      'metal': '#565584',
      'tahiti': '#3ab7bf',
      'silver': '#ecebff',
      'bubble-gum': '#F43F5E',
      'bermuda': '#78dcca',
      'nav-grey': '#787E8C',
      'primary': '#6A38EB',
      'search-bg': 'rgba(236, 236, 244, 0.5)',
      'border': '#F0F0F6',
      'profile-icon': '#B9BDC8',
      'footer-nav': '#1B2230',
      'grey': '#5B6270',
      'grey-bg-footer': '#ECECF4',
      'icon-bg': '#FAFAFC',
      'secondary-text': '#788091',
      'secondary-text-bold': '#5B6270',
      'tabs': '#586070',
      'disabled-input': 'rgba(91, 98, 112, 0.12)',
      'disabled-input-text': '#849DAB',
      'card-text-light': '#6B7280',
      'accordion-when': '#505D68',
      'notification-other-title': '#111827'
    },
    extend: {},
  },
  plugins: [],
}
